#!/bin/sh -e
### BEGIN INIT INFO
# Provides:            crowd
# Required-Start:    $remote_fs $syslog
# Required-Stop:    $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:        0 1 6
# Short-Description: Start crowd at boot.
# Description: Enables crowd service at boot time.
### END INIT INFO
 
# Define some variables
# Name of app
APP=crowd
# Name of the user to run as
USER=root
# Location of application's bin directory
BASE=/opt/crowd
# Location of Java JDK
export JAVA_HOME=/usr/lib/jvm/java-6-sun
 
case "$1" in
# Start command
start)
echo "Starting $APP"
/bin/su -m $USER -c "cd $BASE && $BASE/start_crowd.sh& &> /dev/null"
;;
*)
echo "Usage: /etc/init.d/$APP start"
exit 1
;;
esac
 
exit 0


