#!/bin/sh -e
### BEGIN INIT INFO
# Provides:            jira
# Required-Start:    $remote_fs $syslog
# Required-Stop:    $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:        0 1 6
# Short-Description: Start jira at boot.
# Description: Enables jira service at boot time.
### END INIT INFO

# Define some variables
# Name of app
APP=jira
# Name of the user to run as
USER=root
# Location of application's bin directory
BASE=/opt/jira
# Location of Java JDK
export JAVA_HOME=/usr/lib/jvm/java-6-sun

case "$1" in
# Start command
start)
echo "Starting $APP"
/bin/su -m $USER -c "cd $BASE/logs && $BASE/bin/startup.sh &> /dev/null"
;;
# Stop command
stop)
echo "Stopping $APP"
/bin/su -m $USER -c "$BASE/bin/shutdown.sh &> /dev/null"
echo "$APP stopped successfully"
;;
# Restart command
restart)
$0 stop
sleep 5
$0 start
;;
*)
echo "Usage: /etc/init.d/$APP {start|restart|stop}"
exit 1
;;
esac

exit 0


