---

- import_tasks: install.yml

- name: Find path to the openssl binary
  ansible.builtin.command: which openssl
  changed_when: false
  register: which_openssl_output

- name: Register fact containing path to openssl binary
  ansible.builtin.set_fact:
    dhparam_openssl_binary: "{{ which_openssl_output.stdout_lines[0] }}"
  no_log: true
  check_mode: no

- name: Output directory for Diffie-Hellman parameters exists
  ansible.builtin.file:
    path: "{{ dhparam_file | dirname }}"
    state: directory

- name: The Diffie-Hellman parameter file is generated
  ansible.builtin.command: "{{ dhparam_openssl_binary }} dhparam -out '{{ dhparam_file }}' {{ dhparam_size }}"
  args:
    creates: "{{ dhparam_file }}"
  when: not ansible_check_mode

- import_tasks: cron.yml
  when: not ansible_check_mode
