---

virtualenv_package_name: virtualenv
letsencrypt_depends:
  - python3
  - python3-dev
  - python3-venv
  - python3-pip
  - gcc
  - git
  - dialog
  - libaugeas0
  - libssl-dev
  - libffi-dev
  - ca-certificates
