galaxy_info:
  author: Syed Ahmed
  description: Role for managing sudo files.
  company: "Beaty Consultancy"
  license: license (Apache 2.0)
  min_ansible_version: "2.16"
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - trusty
    - xenial
    - bionic
    - focal
    - jammy
    - noble
  - name: Debian
    versions:
    - squeeze
    - wheezy
    - jessie
  - name: EL
    versions:
    - "6"
    - "7"
  - name: Fedora
    versions:
    - "19"
    - "20"
dependencies: []
