---
- name: rebuild discourse data
  command: './launcher rebuild {{DISCOURSE_DATA_CONTAINER_NAME}}'
  args:
   chdir: '{{ DISCOURSE_INSTALLATION_DIR }}'

- name: rebuild discourse web
  command: './launcher rebuild {{DISCOURSE_WEB_CONTAINER_NAME}}'
  args:
   chdir: '{{ DISCOURSE_INSTALLATION_DIR }}'
