---
galaxy_info:
  author: Nick Hammond
  description: Role to configure logrotate scripts
  license: BSD
  min_ansible_version: "2.16"
  platforms:
  - name: Ubuntu
    versions:
    - lucid
    - precise
    - trusty
    - xenial
    - bionic
    - focal
    - jammy
    - noble
  - name: EL
    versions:
    - "7"
dependencies: []
