galaxy_info:
  author: Osiris Alejandro Gomez
  description: MySQL Backup using mysqldump
  company: gcoop Cooperativa de Software Libre

  license: license GPLv3

  min_ansible_version: 1.9

  github_branch: master

  platforms:

  - name: Debian
    versions:
    - jessie

  galaxy_tags:
    - mysql
    - mysqldump
    - backup

dependencies: []
