---
  - name: install docker-buildx
    apt:
      name: docker-buildx
      state: present

  - name: Stop docker service
    command: systemctl stop docker.service

  - name: Stop docker socket
    command: systemctl stop docker.socket

  - name: Ensure BuildKit configuration directory exists
    file:
      path: /etc/buildkit
      state: directory
      owner: root
      group: root
      mode: 0755

  - name: Configure BuildKit Caching
    copy:
      owner: root
      group: root
      mode: 0644
      src: files/docker/buildkitd.toml
      dest: /etc/buildkit/buildkitd.toml

  - name: Reload docker service
    command: systemctl daemon-reload

  - name: Start docker socket service
    command: systemctl start docker.socket

  - name: Start docker service
    command: systemctl start docker.service

  - name: Switch to default builder
    command: docker buildx use default

  - name: Delete any existing builders
    command: |
      docker buildx rm --all-inactive --force

  - name: Create buildx builder
    command: |
      docker buildx create \
        --name openmrs-builder \
        --driver docker-container \
        --driver-opt image=moby/buildkit:buildx-stable-1 \
        --driver-opt env.BUILDKIT_STEP_LOG_MAX_SIZE=-1
        --driver-opt env.BUILDKIT_STEP_LOG_MAX_SPEED=-1
        --config /etc/buildkit/buildkitd.toml
        --use
