---
  - name: Adding dd-agent to docker group
    user: name='dd-agent'
          groups='docker'
          append=yes
  # https://github.com/docker/compose/issues/4344
  - name: Check if docker-py is installed
    command: pip list | fgrep 'docker-py '
    register: docker_py_installed
    changed_when: docker_py_installed.stdout.find('docker-py') == -1
  - name: Uninstall docker-py
    shell: pip uninstall docker docker-py ; pip install docker==3.5.1
    when: docker_py_installed.stdout.find('docker-py') == -1

  - name: Check if docker was restarted yet
    command: docker info
    register: docker_restarted
    changed_when: docker_restarted.stdout.find('overlay2') == -1

  - name: Restart docker service
    shell: systemctl restart docker
    when: docker_restarted.stdout.find('overlay2') == -1

  - name: Configure datadog service to start after docker
    lineinfile:
       dest: /lib/systemd/system/datadog-agent.service
       regexp: '^After='
       line: "After=network.target docker.service"
       state: present
    notify: restart datadog-agent

  - name: Docker cleanup script copy
    copy:
      src: 'files/docker-cleanup.sh'
      dest: "/usr/sbin/docker-cleanup.sh"
      owner: 'root'
      group: 'root'
      mode: '0700'
  - name: Docker cleanup cron
    cron:
      name: "docker-cleanup"
      minute: "0"
      hour: "2"
      job: "/usr/sbin/docker-cleanup.sh"
      
  - name: Setup docker for ElasticSearch
    sysctl: name={{ item.key }} value={{ item.value }}
    with_items:
      - { key: "vm.max_map_count", value: "262144" }
