---
  - name: LetsEncrypt post renew hook open LDAP restart script
    copy:
      src: 'files/restart-id.sh'
      dest: "/etc/letsencrypt/renewal-hooks/post/restart-id.sh"
      owner: 'root'
      group: 'root'
      mode: '0700'

  - name: lookup letsencrypt private keys
    find:
      paths: /etc/letsencrypt/archive
      file_type: file
      patterns: "priv*"
      recurse: true
    register: privatekeys

  - name: Allow cert access for LDAP user (1001)
    file:
      path: "{{ item.path }}"
      state: file
      mode: "0644"
    with_items: "{{ privatekeys.files }}"