---
# Ensure UFW is installed
- name: Ensure UFW is installed
  ansible.builtin.apt:
    name: ufw
    state: present
  become: true

# Set UFW default policy and enable
- name: Set UFW default policy and enable
  community.general.ufw:
    direction: "{{ ufw_config.globalconfig.direction }}"
    policy: "{{ ufw_config.globalconfig.policy }}"
    state: "{{ ufw_config.globalconfig.state }}"
    logging: "{{ ufw_config.globalconfig.logging }}"
  become: true

# Allow SSH
- name: Allow SSH
  community.general.ufw:
    rule: "{{ ufw_rules.sshd.rule }}"
    port: "{{ ufw_rules.sshd.port }}"
    proto: "{{ ufw_rules.sshd.proto }}"
  become: true