---
# tasks file for hswong3i.bamboo

- name: Create Group
  ansible.builtin.group:
    name: "{{ bamboo_user }}"
    gid: "{{ bamboo_gid | default(None) or omit }}"
  when: bamboo_pass is string and bamboo_hash_salt is string
  notify: restart bamboo
  tags: hswong3i.bamboo

- name: Create User
  ansible.builtin.user:
    name: "{{ bamboo_user }}"
    password: "{{ bamboo_pass | password_hash('sha512', bamboo_hash_salt) }}"
    home: "{{ bamboo_home }}"
    group: "{{ bamboo_user }}"
    uid: "{{ bamboo_uid | default(None) or omit }}"
    shell: "/bin/bash"
  when: bamboo_pass is string and bamboo_hash_salt is string
  notify: restart bamboo
  tags: hswong3i.bamboo

- name: Prepare Files
  ansible.builtin.file:
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: "{{ item.state }}"
  loop:
    - { dest: "{{ bamboo_catalina }}", owner: "{{ bamboo_user }}", group: "{{ bamboo_user }}", mode: "0755", state: "directory" }
  notify: restart bamboo
  tags: hswong3i.bamboo

- name: Download Package
  ansible.builtin.get_url:
    url: "{{ bamboo_url }}"
    dest: "/tmp/{{ bamboo_archive }}"
    checksum: "{{ bamboo_checksum }}"
    mode: '0644'
  tags: hswong3i.bamboo

- name: Unarchive Package
  ansible.builtin.unarchive:
    src: "/tmp/{{ bamboo_archive }}"
    dest: "{{ bamboo_catalina }}"
    remote_src: true
    owner: "{{ bamboo_user }}"
    group: "{{ bamboo_user }}"
    extra_opts:
      - --strip-components=1
    creates: "{{ bamboo_catalina }}/bin/start-bamboo.sh"
  notify: restart bamboo
  tags: hswong3i.bamboo

- name: Copy Templates
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop:
    - { src: "etc/init.d/bamboo.j2", dest: "/etc/init.d/bamboo", owner: "root", group: "root", mode: "0755" }
    - { src: "usr/share/bamboo/bin/setenv.sh.j2",
        dest: "{{ bamboo_catalina }}/bin/setenv.sh",
        owner: "{{ bamboo_user }}",
        group: "{{ bamboo_user }}",
        mode: "0644" }
    - { src: "usr/share/bamboo/conf/server.xml.j2",
        dest: "{{ bamboo_catalina }}/conf/server.xml",
        owner: "{{ bamboo_user }}",
        group: "{{ bamboo_user }}",
        mode: "0644" }
  notify: restart bamboo
  tags: hswong3i.bamboo

- name: Enable Service
  ansible.builtin.service:
    name: "bamboo"
    enabled: "yes"
  notify: restart bamboo
  tags: hswong3i.bamboo
