# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.8.0"

required_plugins = %w( vagrant-vbguest vagrant-serverspec )
required_plugins.each do |plugin|
    exec "vagrant plugin install #{plugin};vagrant #{ARGV.join(" ")}" unless Vagrant.has_plugin? plugin || ARGV[0] == 'plugin'
end

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.provision "shell", inline: <<-SHELL
    set -x
    sudo apt-get update
    sudo apt-get -y install python python-pip
  SHELL

  config.vm.define "docker" do |docker|
    docker.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.galaxy_role_file = 'roles/roles-requirements.yml'
      ansible.playbook = "vagrant.yml"
    end
    docker.vm.provision :serverspec do |spec|
      spec.pattern = 'spec/docker_spec.rb'
    end
  end
end
