---
- name: Install logrotate
  ansible.builtin.package:
    name: logrotate
    state: present
  when: logrotate_scripts is defined and logrotate_scripts | length > 0

- name: Setup logrotate.d scripts
  ansible.builtin.template:
    src: logrotate.d.j2
    dest: "{{ logrotate_conf_dir }}{{ item.name }}"
  loop: "{{ logrotate_scripts }}"
  when: logrotate_scripts is defined
