#!/usr/bin/env ruby

forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs/apt'
mod 'puppetlabs/stdlib'
mod 'maestrodev/wget'
mod 'puppetlabs/docker'
mod 'cintiadr/bamboo_agent'
mod 'puppet/nodejs'
