# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"


Vagrant.require_version '>= 1.8.0'

required_plugins = %w(vagrant-vbguest vagrant-serverspec)
required_plugins.each do |plugin|
  exec "vagrant plugin install #{plugin};vagrant #{ARGV.join(' ')}" unless Vagrant.has_plugin? plugin || ARGV[0] == 'plugin'
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # canonical Ubuntu basebox
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "bamboo-agent.vagrant.openmrs.org"
  config.vm.synced_folder ".", "/etc/openmrs-puppet/"

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
  end

  config.vm.provision "shell", :path => 'bin/first-boot.sh'

  # And running puppet
  config.vm.provision "puppet" do |puppet|
    puppet.module_path = [ 'modules', 'openmrs-modules' ]
    puppet.hiera_config_path = "hiera.yaml"
    puppet.working_directory = "/etc/openmrs-puppet/"
    puppet.manifest_file = 'site.pp'
    puppet.facter = {
     "environment" => "vagrant"
    }
   #    puppet.options = ['--debug']

  end

  # and tests
  config.vm.provision :serverspec do |spec|
    spec.pattern = "spec/*_spec.rb"
  end

end
